language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

## Non-sudo environments are faster
sudo: false

## Cache composer and vendor libraries
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - curl -s http://getcomposer.org/installer | php
  - # 7.4snapshot does not currently have ext-gd - but we don't need it for our tests
  - if [ ${TRAVIS_PHP_VERSION:0:3} > 7.2 ]; then php composer.phar install --no-interaction --ignore-platform-reqs; fi
  - if [ ${TRAVIS_PHP_VERSION:0:3} < 7.3 ]; then php composer.phar install --no-interaction; fi

before_script:
  - travis_retry composer config github-oauth.github.com "${GITHUB_OAUTH_TOKEN}"
  - echo "${TRAVIS_PHP_VERSION}"

script:
  - mkdir -p build/logs
  - # nightly and 7.4snapshot do not currently have ext-xdebug, which is needed for coverage testing
  - if [ ${TRAVIS_PHP_VERSION:0:3} > 7.2 ]; then vendor/bin/phpunit -c phpunit.xml.dist; fi
  - if [ ${TRAVIS_PHP_VERSION:0:3} < 7.3 ]; then vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover tests/clover.xml; fi

after_script:
  - travis_retry php vendor/bin/php-coveralls -v
