name: Code style

on: [push, pull_request]

jobs:
  run:
    if: ${{ !startsWith(github.event.head_commit.message, 'Translation:') }}
    runs-on: ubuntu-latest
    name: PHP/PHTML/CSS

    steps:
      - uses: actions/checkout@v2

      - run: composer validate

      - run: composer global require squizlabs/php_codesniffer

      - name: PHP
        run: ~/.composer/vendor/bin/phpcs --colors --standard=PSR12 --exclude=Generic.Files.LineLength --extensions=php index.php app modules_v4 tests

      - name: Style sheets
        run: ~/.composer/vendor/bin/phpcs --colors --extensions=css resources/css
