name: Static analysis

on: [push, pull_request]

jobs:
  run:
    if: ${{ !startsWith(github.event.head_commit.message, 'Translation:') }}
    runs-on: ${{ matrix.operating-system }}
    name: phpstan

    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-version: ['8.3', '8.4']
      fail-fast: false

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-file: 'development'

      - uses: actions/checkout@v4

      - run: composer validate

      - run: composer global config --no-plugins allow-plugins.phpstan/extension-installer true

      - run: composer global require phpstan/phpstan phpstan/extension-installer phpstan/phpstan-deprecation-rules phpstan/phpstan-strict-rules phpstan/phpstan-phpunit

      - run: composer install --no-progress

      - run: ~/.composer/vendor/bin/phpstan analyze --no-progress --level=max app index.php
